openapi: 3.0.2
info:
  title: Lunchtime API
  version: 0.1.3
  description: Calculates working time for a restaurant
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  contact:
    name: Ruslan Gainutdinov
    email: support@ruslan.org
    url: 'https://github.com/huksley/lunchtime'
servers:
  - url: /
tags:
  - name: Common
    description: Common API, available to everyone without authentication
paths:
  "/schedule/readable":
    description: Format readable working time1
    summary: Format readable working time3
    post:
      summary: Format readable working time
      requestBody:
        description: Input schedule
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IntermediateSchedule"
            examples:
              SampleRequest:
                summary: Example of request
                externalValue: ./example-request.json
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HumanReadableSchedule"
              examples:
                SampleResponse:
                  summary: Example of response
                  externalValue: ./example-response.json
          description: Readable schedule
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    ScheduleEvent:
      type: object
      properties:
        type:
          type: string
          enum:
            - OPEN
            - CLOSE
        value:
          type: integer
    ScheduleEvents:
      type: array
      items:
        $ref: "#/components/schemas/ScheduleEvent"
    IntermediateSchedule:
      type: object
      properties:
        monday:
          $ref: "#/components/schemas/ScheduleEvents"
        tuesday:
          $ref: "#/components/schemas/ScheduleEvents"
        wednesday:
          $ref: "#/components/schemas/ScheduleEvents"
        thursday:
          $ref: "#/components/schemas/ScheduleEvents"
        friday:
          $ref: "#/components/schemas/ScheduleEvents"
        saturay:
          $ref: "#/components/schemas/ScheduleEvents"
        sunday:
          $ref: "#/components/schemas/ScheduleEvents"
    HumanReadableSchedule:
      description: List of lines of schedule
      type: array
      items:
        type: string
    Error:
      type: object
      properties:
        code:
          type: number
          example: 500
        message:
          type: string
          example: "Invalid input: ABC"
