name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: "11.0.4"
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}
            ${{ runner.os }}-build-${{ matrix.node-version }}
            ${{ runner.os }}-${{ matrix.node-version }}
      - name: Build with Gradle
        run: ./gradlew npmInstall npmBuild build
      - name: Update API documentation
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: src/main/resources/
          dst_path: /
          dst_owner: huksley
          dst_repo_name: lunchtime
          dst_branch: docs
          filter: openapi.yaml example-request.json example-response.json
          commit_message: Update documentation files
      - name: Update API documentation
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          src_path: src/main/resources/generated
          dst_path: /
          dst_owner: huksley
          dst_repo_name: lunchtime
          dst_branch: docs
          filter: redoc.html
          commit_message: Update documentation files